export type ProjectStatus = 'Current' | 'Overdue' | 'On Hold' | 'Completed' | 'Archived';

export interface TeamMember {
  initials: string;
  name: string;
  color: string;
}

export type InvoiceType = 'bundled' | 'individual';

export interface Project {
  id: string;
  title: string;
  status: ProjectStatus;
  client: { name: string; color: string };
  serviceType: { label: string; departmentId: string };
  /** Optional account manager responsible for the client relationship. */
  accountManager?: TeamMember;
  teamLeads: TeamMember[];
  assignees: TeamMember[];
  progress: number;
  tasksCompleted: number;
  tasksTotal: number;
  dueDate: string;
  /** Optional ISO date for Upcoming urgency buckets; due date is the fallback. */
  startDate?: string;
  /** ISO date (YYYY-MM-DD) on which the project was placed on hold */
  holdDate?: string;
  /** ISO date (YYYY-MM-DD) on which the project was actually completed */
  completedDate?: string;
  badge?: number;
  /** How this project is invoiced */
  invoiceType?: InvoiceType;
  /** Revenue amount in AED */
  revenue?: number;
  /** Reason provided when the project was placed on hold */
  holdReason?: string;
  /** Reason provided when the project was deleted / archived */
  deleteReason?: string;
  /** Reason provided when the project team was reassigned */
  reassignReason?: string;
}

const SEED_PROJECTS: Project[] = [
  {
    id: '1',
    title: 'VAT Filing Jul 2025 – Sep 2025',
    status: 'Current',
    client: { name: 'Nexora', color: '#334756' },
    serviceType: { label: 'Accounting', departmentId: 'dept-1' },
    teamLeads: [{ initials: 'AK', name: 'Arjun Kumar', color: '#F16611' }],
    assignees: [{ initials: 'MK', name: 'Mohammed Khan', color: '#334756' }],
    progress: 0,
    tasksCompleted: 0,
    tasksTotal: 12,
    dueDate: 'Due 03 Jul 2026',
    badge: 1,
    invoiceType: 'bundled' as const,
    revenue: 4500,
    reassignReason: 'Arjun Kumar has moved to a different client portfolio. Ivan Xavier has been assigned as the new Account Manager effective immediately.',
  },
  {
    id: '2',
    title: 'Book Keeping – Sep 2025',
    status: 'Current',
    client: { name: 'Finovo', color: '#F16611' },
    serviceType: { label: 'Finance', departmentId: 'dept-2' },
    teamLeads: [{ initials: 'AM', name: 'Aisha Mohammed', color: '#334756' }],
    assignees: [{ initials: 'TI', name: 'Tariq Ibrahim', color: '#22C55E' }],
    progress: 30,
    tasksCompleted: 5,
    tasksTotal: 12,
    dueDate: 'Due 20 Jun 2025',
    badge: 28,
    invoiceType: 'individual' as const,
    revenue: 8200,
  },
  {
    id: '3',
    title: 'CT Registration – June 2026',
    status: 'Overdue',
    client: { name: 'Lumo', color: '#22C55E' },
    serviceType: { label: 'IT', departmentId: 'dept-6' },
    teamLeads: [{ initials: 'IX', name: 'Ivan Xavier', color: '#334756' }],
    assignees: [],
    progress: 0,
    tasksCompleted: 0,
    tasksTotal: 12,
    dueDate: 'Due 30 Jun 2025',
    badge: 36,
    invoiceType: 'bundled' as const,
    revenue: 3750,
  },
  {
    id: '4',
    title: 'CT Registration – Nov 2025',
    status: 'On Hold',
    client: { name: 'Talvo', color: '#334756' },
    serviceType: { label: 'IT', departmentId: 'dept-6' },
    teamLeads: [{ initials: 'AT', name: 'Ali Tariq', color: '#F16611' }],
    assignees: [],
    progress: 0,
    tasksCompleted: 0,
    tasksTotal: 12,
    dueDate: 'Due 25 May 2026',
    holdReason: 'Client requested a temporary pause while they gather outstanding trade licence documents. Expected to resume within 3–4 weeks.',
    holdDate: '2026-07-28',
    badge: 1,
    invoiceType: 'individual' as const,
    revenue: 12000,
  },
  {
    id: '5',
    title: 'Bookkeeping – Oct 2025',
    status: 'Current',
    client: { name: 'Orvix', color: '#0A2B3B' },
    serviceType: { label: 'Technology', departmentId: 'dept-6' },
    teamLeads: [{ initials: 'AT', name: 'Ali Tariq', color: '#22C55E' }],
    assignees: [{ initials: 'MM', name: 'Maya Martinez', color: '#334756' }],
    progress: 0,
    tasksCompleted: 0,
    tasksTotal: 12,
    dueDate: 'Due 20 Jul 2025',
    badge: 11,
    invoiceType: 'bundled' as const,
    revenue: 6800,
  },
  {
    id: '6',
    title: 'Payroll Management – Q4 2025',
    status: 'Current',
    client: { name: 'Stratco', color: '#F16611' },
    serviceType: { label: 'HR', departmentId: 'dept-5' },
    teamLeads: [{ initials: 'DK', name: 'David Kim', color: '#334756' }],
    assignees: [
      { initials: 'AT', name: 'Ali Tariq', color: '#F16611' },
      { initials: 'KS', name: 'Karen Simmons', color: '#22C55E' },
      { initials: 'VC', name: 'Vera Chen', color: '#334756' },
    ],
    progress: 75,
    tasksCompleted: 8,
    tasksTotal: 10,
    dueDate: 'Due 30 Sep 2026',
    badge: 5,
    invoiceType: 'individual' as const,
    revenue: 9500,
  },
  {
    id: '7',
    title: 'Annual Audit – FY 2025',
    status: 'Completed',
    client: { name: 'Nexora', color: '#334756' },
    serviceType: { label: 'Accounting', departmentId: 'dept-1' },
    teamLeads: [{ initials: 'KT', name: 'Karim Tahir', color: '#F16611' }],
    assignees: [{ initials: 'TP', name: 'Tina Patel', color: '#22C55E' }],
    progress: 100,
    tasksCompleted: 12,
    tasksTotal: 12,
    dueDate: 'Due 15 Apr 2025',
    completedDate: '2025-05-02',   // 17 days late
    badge: 0,
    invoiceType: 'bundled' as const,
    revenue: 2500,
  },
  {
    id: '8',
    title: 'VAT Compliance – Jan 2026',
    status: 'Overdue',
    client: { name: 'Finovo', color: '#F16611' },
    serviceType: { label: 'Finance', departmentId: 'dept-2' },
    teamLeads: [{ initials: 'PT', name: 'Paulo Torres', color: '#334756' }],
    assignees: [
      { initials: 'SN', name: 'Sarah Nasser', color: '#F16611' },
      { initials: 'HK', name: 'Hassan Khalid', color: '#22C55E' },
      { initials: 'VC', name: 'Vera Chen', color: '#334756' },
      { initials: 'OR', name: 'Omar Rahman', color: '#F16611' },
    ],
    progress: 20,
    tasksCompleted: 2,
    tasksTotal: 10,
    dueDate: 'Due 31 Dec 2025',
    badge: 14,
    invoiceType: 'individual' as const,
    revenue: 15000,
  },
  {
    id: '9',
    title: 'Corporate Tax Return – Q1 2026',
    status: 'Current',
    client: { name: 'Nexora', color: '#334756' },
    serviceType: { label: 'Accounting', departmentId: 'dept-1' },
    teamLeads: [{ initials: 'MN', name: 'Meera Nair', color: '#22C55E' }],
    assignees: [
      { initials: 'NS', name: 'Nadia Saleh', color: '#F16611' },
      { initials: 'VC', name: 'Vera Chen', color: '#334756' },
      { initials: 'OR', name: 'Omar Rahman', color: '#F16611' },
      { initials: 'LH', name: 'Lina Haddad', color: '#22C55E' },
      { initials: 'BM', name: 'Bilal Mahmoud', color: '#334756' },
    ],
    progress: 95,
    tasksCompleted: 8,
    tasksTotal: 9,
    dueDate: 'Due 10 Aug 2025',
    badge: 3,
    invoiceType: 'bundled' as const,
    revenue: 5200,
  },
  {
    id: '10',
    title: 'Financial Statements – Mar 2026',
    status: 'Current',
    client: { name: 'Lumo', color: '#22C55E' },
    serviceType: { label: 'Finance', departmentId: 'dept-2' },
    teamLeads: [{ initials: 'MK', name: 'Mohammed Khan', color: '#334756' }],
    assignees: [{ initials: 'PN', name: 'Priya Nair', color: '#F16611' }],
    progress: 80,
    tasksCompleted: 8,
    tasksTotal: 10,
    dueDate: 'Due 25 Aug 2026',
    badge: 7,
    invoiceType: 'individual' as const,
    revenue: 7800,
  },
  {
    id: '11',
    title: 'Corporate Tax Registration – FY 2026',
    status: 'Overdue',
    client: { name: 'Stratco', color: '#F16611' },
    serviceType: { label: 'Compliance', departmentId: 'dept-4' },
    teamLeads: [{ initials: 'LN', name: 'Laura Nixon', color: '#334756' }],
    assignees: [{ initials: 'QA', name: 'Qasim Ahmed', color: '#22C55E' }],
    progress: 42,
    tasksCompleted: 5,
    tasksTotal: 12,
    dueDate: 'Due 18 Jun 2026',
    badge: 9,
    invoiceType: 'bundled' as const,
    revenue: 4100,
  },
  {
    id: '12',
    title: 'VAT Registration – Talvo',
    status: 'On Hold',
    client: { name: 'Talvo', color: '#334756' },
    serviceType: { label: 'Compliance', departmentId: 'dept-4' },
    teamLeads: [{ initials: 'GH', name: 'Grace Hassan', color: '#F16611' }],
    assignees: [
      { initials: 'YM', name: 'Yousef Mansour', color: '#22C55E' },
      { initials: 'EF', name: 'Elena Flores', color: '#334756' },
    ],
    progress: 15,
    tasksCompleted: 2,
    tasksTotal: 13,
    dueDate: 'Due 15 Jun 2026',
    holdDate: '2026-07-20',
    holdReason: 'Awaiting updated VAT registration certificate from the client before proceeding. Finance team flagged a discrepancy in the submitted documents.',
    badge: 2,
    invoiceType: 'individual' as const,
    revenue: 11000,
  },
  {
    id: '13',
    title: 'Annual Returns – Lumo 2025',
    status: 'Completed',
    client: { name: 'Lumo', color: '#22C55E' },
    serviceType: { label: 'Accounting', departmentId: 'dept-1' },
    teamLeads: [{ initials: 'RW', name: 'Rania Williams', color: '#334756' }],
    assignees: [{ initials: 'BE', name: 'Bilal Ebrahim', color: '#F16611' }],
    progress: 100,
    tasksCompleted: 10,
    tasksTotal: 10,
    dueDate: 'Due 28 Feb 2026',
    completedDate: '2026-02-20',   // on time
    badge: 0,
    invoiceType: 'bundled' as const,
    revenue: 6300,
  },
  {
    id: '14',
    title: 'Year-End Audit 2026 – Lumo',
    status: 'Current',
    client: { name: 'Lumo', color: '#22C55E' },
    serviceType: { label: 'Audit', departmentId: 'dept-3' },
    teamLeads: [{ initials: 'SK', name: 'Sofia Khan', color: '#F16611' }],
    assignees: [
      { initials: 'TW', name: 'Thomas Wright', color: '#334756' },
      { initials: 'EF', name: 'Elena Flores', color: '#22C55E' },
    ],
    progress: 65,
    tasksCompleted: 7,
    tasksTotal: 11,
    dueDate: 'Due 30 Sep 2026',
    badge: 4,
    invoiceType: 'individual' as const,
    revenue: 8900,
  },
  {
    id: '15',
    title: 'FY2024 Audit – Nexora',
    status: 'Archived',
    client: { name: 'Nexora', color: '#334756' },
    serviceType: { label: 'Audit', departmentId: 'dept-3' },
    teamLeads: [{ initials: 'JM', name: 'Jamal Malik', color: '#334756' }],
    assignees: [
      { initials: 'BE', name: 'Bilal Ebrahim', color: '#F16611' },
      { initials: 'QA', name: 'Qasim Ahmed', color: '#22C55E' },
    ],
    progress: 100,
    tasksCompleted: 12,
    tasksTotal: 12,
    dueDate: 'Due 31 Dec 2025',
    deleteReason: 'Audit scope was merged into the FY2024 Combined Audit – Nexora project at the client\'s request. All tasks and documents transferred accordingly.',
    badge: 0,
    invoiceType: 'bundled' as const,
    revenue: 3200,
  },
  {
    id: '16',
    title: 'Compliance Review – FY 2025',
    status: 'Completed',
    client: { name: 'Finovo', color: '#F16611' },
    serviceType: { label: 'Compliance', departmentId: 'dept-4' },
    teamLeads: [{ initials: 'NK', name: 'Nadia Khan', color: '#22C55E' }],
    assignees: [{ initials: 'LN', name: 'Laura Nixon', color: '#334756' }],
    progress: 100,
    tasksCompleted: 14,
    tasksTotal: 14,
    dueDate: 'Due 31 Jan 2026',
    completedDate: '2026-02-14',   // 14 days late
    badge: 0,
    invoiceType: 'individual' as const,
    revenue: 13500,
  },
  {
    id: '17',
    title: 'Regulatory Filing – Orvix Q3',
    status: 'Current',
    client: { name: 'Orvix', color: '#0A2B3B' },
    serviceType: { label: 'Compliance', departmentId: 'dept-4' },
    teamLeads: [{ initials: 'OA', name: 'Omar Abdulla', color: '#F16611' }],
    assignees: [{ initials: 'GH', name: 'Grace Hassan', color: '#334756' }],
    progress: 25,
    tasksCompleted: 2,
    tasksTotal: 8,
    dueDate: 'Due 30 Sep 2026',
    badge: 6,
    invoiceType: 'bundled' as const,
    revenue: 5800,
  },
  {
    id: '18',
    title: 'Payroll Reconciliation – Q2',
    status: 'Overdue',
    client: { name: 'Stratco', color: '#F16611' },
    serviceType: { label: 'HR', departmentId: 'dept-5' },
    teamLeads: [{ initials: 'MT', name: 'Maya Thomas', color: '#334756' }],
    assignees: [{ initials: 'TW', name: 'Thomas Wright', color: '#22C55E' }],
    progress: 55,
    tasksCompleted: 6,
    tasksTotal: 11,
    dueDate: 'Due 12 Jul 2026',
    badge: 18,
    invoiceType: 'individual' as const,
    revenue: 7200,
  },
  {
    id: '19',
    title: 'Management Accounts – Q3',
    status: 'On Hold',
    client: { name: 'Finovo', color: '#F16611' },
    serviceType: { label: 'Finance', departmentId: 'dept-2' },
    teamLeads: [{ initials: 'RE', name: 'Rami El-Sayed', color: '#22C55E' }],
    assignees: [],
    progress: 35,
    tasksCompleted: 4,
    tasksTotal: 10,
    dueDate: 'Due 05 Oct 2026',
    holdDate: '2026-08-05',
    holdReason: 'Management has requested a strategic review of Q3 figures before the accounts are finalised. Project will resume once internal sign-off is received.',
    badge: 3,
    invoiceType: 'bundled' as const,
    revenue: 4800,
  },
  {
    id: '20',
    title: 'Financial Close – December 2025',
    status: 'Completed',
    client: { name: 'Orvix', color: '#0A2B3B' },
    serviceType: { label: 'Finance', departmentId: 'dept-2' },
    teamLeads: [{ initials: 'SA', name: 'Sara Ali', color: '#F16611' }],
    assignees: [{ initials: 'JM', name: 'Jamal Malik', color: '#334756' }],
    progress: 100,
    tasksCompleted: 9,
    tasksTotal: 9,
    dueDate: 'Due 20 Jan 2026',
    completedDate: '2026-01-18',   // on time
    badge: 0,
    invoiceType: 'individual' as const,
    revenue: 10500,
  },
  {
    id: '21',
    title: 'VAT Return – Q2 2026',
    status: 'Current',
    client: { name: 'Talvo', color: '#334756' },
    serviceType: { label: 'Accounting', departmentId: 'dept-1' },
    teamLeads: [{ initials: 'NA', name: 'Noura Ahmed', color: '#F16611' }],
    assignees: [{ initials: 'HS', name: 'Huda Saleh', color: '#22C55E' }],
    progress: 60,
    tasksCompleted: 6,
    tasksTotal: 10,
    dueDate: 'Due 18 Aug 2026',
    badge: 2,
    invoiceType: 'bundled' as const,
    revenue: 6100,
  },
  {
    id: '22',
    title: 'Payroll Setup – FY 2026',
    status: 'Current',
    client: { name: 'Nexora', color: '#334756' },
    serviceType: { label: 'HR', departmentId: 'dept-5' },
    teamLeads: [{ initials: 'FA', name: 'Farah Ali', color: '#22C55E' }],
    assignees: [{ initials: 'OM', name: 'Omar Mansour', color: '#334756' }],
    progress: 45,
    tasksCompleted: 5,
    tasksTotal: 11,
    dueDate: 'Due 24 Aug 2026',
    badge: 1,
    invoiceType: 'individual' as const,
    revenue: 9800,
  },
  {
    id: '23',
    title: 'Corporate Tax Filing – FY 2025',
    status: 'Overdue',
    client: { name: 'Lumo', color: '#22C55E' },
    serviceType: { label: 'Compliance', departmentId: 'dept-4' },
    teamLeads: [{ initials: 'YA', name: 'Yasmin Ahmed', color: '#F16611' }],
    assignees: [{ initials: 'RA', name: 'Rashid Ahmed', color: '#334756' }],
    progress: 35,
    tasksCompleted: 4,
    tasksTotal: 12,
    dueDate: 'Due 22 Jul 2026',
    badge: 12,
    invoiceType: 'bundled' as const,
    revenue: 3900,
  },
  {
    id: '24',
    title: 'Monthly Bookkeeping – May 2026',
    status: 'Completed',
    client: { name: 'Stratco', color: '#F16611' },
    serviceType: { label: 'Finance', departmentId: 'dept-2' },
    teamLeads: [{ initials: 'MS', name: 'Mariam Saeed', color: '#334756' }],
    assignees: [{ initials: 'AK', name: 'Arjun Kumar', color: '#F16611' }],
    progress: 100,
    tasksCompleted: 12,
    tasksTotal: 12,
    dueDate: 'Due 10 Jun 2026',
    completedDate: '2026-06-14',
    badge: 0,
    invoiceType: 'individual' as const,
    revenue: 14000,
  },
  {
    id: '25',
    title: 'License Renewal – Orvix',
    status: 'On Hold',
    client: { name: 'Orvix', color: '#0A2B3B' },
    serviceType: { label: 'Compliance', departmentId: 'dept-4' },
    teamLeads: [{ initials: 'LH', name: 'Lina Haddad', color: '#22C55E' }],
    assignees: [],
    progress: 20,
    tasksCompleted: 2,
    tasksTotal: 10,
    dueDate: 'Due 12 Sep 2026',
    holdDate: '2026-06-25',
    badge: 4,
    invoiceType: 'bundled' as const,
    revenue: 5500,
  },
  {
    id: '26',
    title: 'Internal Controls Review – Q3',
    status: 'Current',
    client: { name: 'Finovo', color: '#F16611' },
    serviceType: { label: 'Audit', departmentId: 'dept-3' },
    teamLeads: [{ initials: 'HK', name: 'Hassan Khalid', color: '#334756' }],
    assignees: [{ initials: 'SN', name: 'Sarah Nasser', color: '#F16611' }],
    progress: 25,
    tasksCompleted: 3,
    tasksTotal: 12,
    dueDate: 'Due 05 Sep 2026',
    badge: 3,
    invoiceType: 'individual' as const,
    revenue: 7600,
  },
  {
    id: '27',
    title: 'WPS Compliance Check – July',
    status: 'Overdue',
    client: { name: 'Talvo', color: '#334756' },
    serviceType: { label: 'HR', departmentId: 'dept-5' },
    teamLeads: [{ initials: 'DK', name: 'David Kim', color: '#334756' }],
    assignees: [{ initials: 'YM', name: 'Yousef Mansour', color: '#22C55E' }],
    progress: 70,
    tasksCompleted: 7,
    tasksTotal: 10,
    dueDate: 'Due 28 Jul 2026',
    badge: 6,
    invoiceType: 'bundled' as const,
    revenue: 4200,
  },
  {
    id: '28',
    title: 'Financial Forecast – H2 2026',
    status: 'Current',
    client: { name: 'Lumo', color: '#22C55E' },
    serviceType: { label: 'Finance', departmentId: 'dept-2' },
    teamLeads: [{ initials: 'PN', name: 'Priya Nair', color: '#F16611' }],
    assignees: [{ initials: 'BE', name: 'Bilal Ebrahim', color: '#F16611' }],
    progress: 50,
    tasksCompleted: 5,
    tasksTotal: 10,
    dueDate: 'Due 29 Aug 2026',
    badge: 2,
    invoiceType: 'individual' as const,
    revenue: 11500,
  },
  {
    id: '29',
    title: 'Audit Evidence Collection – FY 2025',
    status: 'Completed',
    client: { name: 'Nexora', color: '#334756' },
    serviceType: { label: 'Audit', departmentId: 'dept-3' },
    teamLeads: [{ initials: 'SK', name: 'Sofia Khan', color: '#F16611' }],
    assignees: [{ initials: 'TW', name: 'Thomas Wright', color: '#334756' }],
    progress: 100,
    tasksCompleted: 15,
    tasksTotal: 15,
    dueDate: 'Due 25 May 2026',
    completedDate: '2026-05-25',
    badge: 0,
    invoiceType: 'bundled' as const,
    revenue: 6600,
  },
  {
    id: '30',
    title: 'Economic Substance Notification',
    status: 'Archived',
    client: { name: 'Orvix', color: '#0A2B3B' },
    serviceType: { label: 'Compliance', departmentId: 'dept-4' },
    teamLeads: [{ initials: 'OA', name: 'Omar Abdulla', color: '#F16611' }],
    assignees: [{ initials: 'QA', name: 'Qasim Ahmed', color: '#22C55E' }],
    progress: 100,
    tasksCompleted: 8,
    tasksTotal: 8,
    dueDate: 'Due 30 Apr 2026',
    badge: 0,
    invoiceType: 'individual' as const,
    revenue: 8400,
  },
  {
    id: '31',
    title: 'Management Accounts – June 2026',
    status: 'Current',
    client: { name: 'Stratco', color: '#F16611' },
    serviceType: { label: 'Accounting', departmentId: 'dept-1' },
    teamLeads: [{ initials: 'RE', name: 'Rami El-Sayed', color: '#22C55E' }],
    assignees: [{ initials: 'MM', name: 'Maya Martinez', color: '#334756' }],
    progress: 80,
    tasksCompleted: 8,
    tasksTotal: 10,
    dueDate: 'Due 12 Aug 2026',
    badge: 1,
    invoiceType: 'bundled' as const,
    revenue: 3500,
  },
  {
    id: '32',
    title: 'VAT Reconciliation – Q1 2026',
    status: 'Overdue',
    client: { name: 'Finovo', color: '#F16611' },
    serviceType: { label: 'Accounting', departmentId: 'dept-1' },
    teamLeads: [{ initials: 'AM', name: 'Aisha Mohammed', color: '#334756' }],
    assignees: [{ initials: 'MK', name: 'Mohammed Khan', color: '#334756' }],
    progress: 55,
    tasksCompleted: 6,
    tasksTotal: 11,
    dueDate: 'Due 15 Jul 2026',
    badge: 19,
    invoiceType: 'individual' as const,
    revenue: 12500,
  },
  {
    id: '33',
    title: 'Business License Amendment',
    status: 'On Hold',
    client: { name: 'Lumo', color: '#22C55E' },
    serviceType: { label: 'Compliance', departmentId: 'dept-4' },
    teamLeads: [{ initials: 'GH', name: 'Grace Hassan', color: '#F16611' }],
    assignees: [{ initials: 'EF', name: 'Elena Flores', color: '#22C55E' }],
    progress: 10,
    tasksCompleted: 1,
    tasksTotal: 10,
    dueDate: 'Due 20 Aug 2026',
    holdDate: '2026-08-01',
    badge: 1,
    invoiceType: 'bundled' as const,
    revenue: 5900,
  },
  {
    id: '34',
    title: 'Year-End Closing – FY 2025',
    status: 'Completed',
    client: { name: 'Talvo', color: '#334756' },
    serviceType: { label: 'Finance', departmentId: 'dept-2' },
    teamLeads: [{ initials: 'SA', name: 'Sara Ali', color: '#F16611' }],
    assignees: [{ initials: 'JM', name: 'Jamal Malik', color: '#334756' }],
    progress: 100,
    tasksCompleted: 14,
    tasksTotal: 14,
    dueDate: 'Due 15 Mar 2026',
    completedDate: '2026-03-23',
    badge: 0,
    invoiceType: 'individual' as const,
    revenue: 7100,
  },
  {
    id: '35',
    title: 'Corporate Tax Registration – New Entity',
    status: 'Current',
    client: { name: 'Orvix', color: '#0A2B3B' },
    serviceType: { label: 'Compliance', departmentId: 'dept-4' },
    teamLeads: [{ initials: 'LN', name: 'Laura Nixon', color: '#334756' }],
    assignees: [{ initials: 'OR', name: 'Omar Rahman', color: '#F16611' }],
    progress: 30,
    tasksCompleted: 3,
    tasksTotal: 10,
    dueDate: 'Due 14 Sep 2026',
    badge: 2,
    invoiceType: 'bundled' as const,
    revenue: 4600,
  },
  {
    id: '36',
    title: 'External Audit – Interim Review',
    status: 'Current',
    client: { name: 'Nexora', color: '#334756' },
    serviceType: { label: 'Audit', departmentId: 'dept-3' },
    teamLeads: [{ initials: 'KT', name: 'Karim Tahir', color: '#F16611' }],
    assignees: [{ initials: 'TP', name: 'Tina Patel', color: '#22C55E' }],
    progress: 40,
    tasksCompleted: 4,
    tasksTotal: 10,
    dueDate: 'Due 22 Sep 2026',
    badge: 5,
    invoiceType: 'individual' as const,
    revenue: 10000,
  },
  {
    id: '37',
    title: 'Payroll Reconciliation – June 2026',
    status: 'Overdue',
    client: { name: 'Lumo', color: '#22C55E' },
    serviceType: { label: 'HR', departmentId: 'dept-5' },
    teamLeads: [{ initials: 'MT', name: 'Maya Thomas', color: '#334756' }],
    assignees: [{ initials: 'KS', name: 'Karen Simmons', color: '#22C55E' }],
    progress: 65,
    tasksCompleted: 7,
    tasksTotal: 11,
    dueDate: 'Due 31 Jul 2026',
    badge: 3,
    invoiceType: 'bundled' as const,
    revenue: 6400,
  },
  {
    id: '38',
    title: 'Annual Compliance Calendar – 2026',
    status: 'On Hold',
    client: { name: 'Stratco', color: '#F16611' },
    serviceType: { label: 'Compliance', departmentId: 'dept-4' },
    teamLeads: [{ initials: 'NK', name: 'Nadia Khan', color: '#22C55E' }],
    assignees: [],
    progress: 25,
    tasksCompleted: 2,
    tasksTotal: 8,
    dueDate: 'Due 30 Nov 2026',
    holdDate: '2026-07-01',
    badge: 2,
    invoiceType: 'individual' as const,
    revenue: 9200,
  },
  {
    id: '39',
    title: 'Budget Planning – FY 2027',
    status: 'Current',
    client: { name: 'Finovo', color: '#F16611' },
    serviceType: { label: 'Finance', departmentId: 'dept-2' },
    teamLeads: [{ initials: 'MN', name: 'Meera Nair', color: '#22C55E' }],
    assignees: [{ initials: 'NS', name: 'Nadia Saleh', color: '#F16611' }],
    progress: 15,
    tasksCompleted: 2,
    tasksTotal: 12,
    dueDate: 'Due 30 Sep 2026',
    badge: 3,
    invoiceType: 'bundled' as const,
    revenue: 3700,
  },
  {
    id: '40',
    title: 'Deregistration Review – Orvix',
    status: 'Archived',
    client: { name: 'Orvix', color: '#0A2B3B' },
    serviceType: { label: 'Compliance', departmentId: 'dept-4' },
    teamLeads: [{ initials: 'RW', name: 'Rania Williams', color: '#22C55E' }],
    assignees: [{ initials: 'BE', name: 'Bilal Ebrahim', color: '#F16611' }],
    progress: 100,
    tasksCompleted: 9,
    tasksTotal: 9,
    dueDate: 'Due 15 Feb 2026',
    badge: 0,
    invoiceType: 'individual' as const,
    revenue: 13000,
  },
  {
    id: '41',
    title: 'VAT Filing – Q3 2026',
    status: 'Current',
    client: { name: 'Nexora', color: '#334756' },
    serviceType: { label: 'Accounting', departmentId: 'dept-1' },
    teamLeads: [{ initials: 'AK', name: 'Arjun Kumar', color: '#F16611' }],
    assignees: [{ initials: 'HS', name: 'Huda Saleh', color: '#22C55E' }],
    progress: 35,
    tasksCompleted: 4,
    tasksTotal: 12,
    dueDate: 'Due 28 Sep 2026',
    badge: 2,
    invoiceType: 'bundled' as const,
    revenue: 5300,
  },
  {
    id: '42',
    title: 'Monthly Close – August 2026',
    status: 'Current',
    client: { name: 'Talvo', color: '#334756' },
    serviceType: { label: 'Finance', departmentId: 'dept-2' },
    teamLeads: [{ initials: 'SA', name: 'Sara Ali', color: '#F16611' }],
    assignees: [{ initials: 'MK', name: 'Mohammed Khan', color: '#334756' }],
    progress: 60,
    tasksCompleted: 7,
    tasksTotal: 12,
    dueDate: 'Due 31 Aug 2026',
    badge: 4,
    invoiceType: 'individual' as const,
    revenue: 7900,
  },
  {
    id: '43',
    title: 'Employee Benefits Audit – 2026',
    status: 'Current',
    client: { name: 'Orvix', color: '#0A2B3B' },
    serviceType: { label: 'HR', departmentId: 'dept-5' },
    teamLeads: [{ initials: 'DK', name: 'David Kim', color: '#334756' }],
    assignees: [{ initials: 'KS', name: 'Karen Simmons', color: '#22C55E' }],
    progress: 10,
    tasksCompleted: 1,
    tasksTotal: 10,
    dueDate: 'Due 15 Oct 2026',
    badge: 1,
    invoiceType: 'bundled' as const,
    revenue: 4400,
  },
  {
    id: '44',
    title: 'Internal Audit Plan – FY 2027',
    status: 'Current',
    client: { name: 'Stratco', color: '#F16611' },
    serviceType: { label: 'Audit', departmentId: 'dept-3' },
    teamLeads: [{ initials: 'SK', name: 'Sofia Khan', color: '#F16611' }],
    assignees: [{ initials: 'TP', name: 'Tina Patel', color: '#22C55E' }],
    progress: 85,
    tasksCompleted: 9,
    tasksTotal: 11,
    dueDate: 'Due 30 Oct 2026',
    badge: 6,
    invoiceType: 'individual' as const,
    revenue: 11800,
  },
  {
    id: '45',
    title: 'Corporate Tax Return – Q2 2026',
    status: 'Overdue',
    client: { name: 'Lumo', color: '#22C55E' },
    serviceType: { label: 'Compliance', departmentId: 'dept-4' },
    teamLeads: [{ initials: 'LN', name: 'Laura Nixon', color: '#334756' }],
    assignees: [{ initials: 'QA', name: 'Qasim Ahmed', color: '#22C55E' }],
    progress: 48,
    tasksCompleted: 5,
    tasksTotal: 12,
    dueDate: 'Due 25 Jul 2026',
    badge: 10,
    invoiceType: 'bundled' as const,
    revenue: 6700,
  },
  {
    id: '46',
    title: 'Payroll Reconciliation – July 2026',
    status: 'Overdue',
    client: { name: 'Finovo', color: '#F16611' },
    serviceType: { label: 'HR', departmentId: 'dept-5' },
    teamLeads: [{ initials: 'MT', name: 'Maya Thomas', color: '#334756' }],
    assignees: [{ initials: 'TW', name: 'Thomas Wright', color: '#334756' }],
    progress: 70,
    tasksCompleted: 8,
    tasksTotal: 11,
    dueDate: 'Due 05 Jul 2026',
    badge: 30,
    invoiceType: 'individual' as const,
    revenue: 8600,
  },
  {
    id: '47',
    title: 'Business Valuation Review',
    status: 'On Hold',
    client: { name: 'Nexora', color: '#334756' },
    serviceType: { label: 'Finance', departmentId: 'dept-2' },
    teamLeads: [{ initials: 'MN', name: 'Meera Nair', color: '#22C55E' }],
    assignees: [],
    progress: 40,
    tasksCompleted: 4,
    tasksTotal: 10,
    dueDate: 'Due 20 Nov 2026',
    holdDate: '2026-05-20',
    badge: 5,
    invoiceType: 'bundled' as const,
    revenue: 3300,
  },
  {
    id: '48',
    title: 'VAT Voluntary Disclosure',
    status: 'On Hold',
    client: { name: 'Orvix', color: '#0A2B3B' },
    serviceType: { label: 'Compliance', departmentId: 'dept-4' },
    teamLeads: [{ initials: 'GH', name: 'Grace Hassan', color: '#F16611' }],
    assignees: [{ initials: 'EF', name: 'Elena Flores', color: '#334756' }],
    progress: 20,
    tasksCompleted: 2,
    tasksTotal: 10,
    dueDate: 'Due 12 Dec 2026',
    holdDate: '2026-08-10',
    badge: 2,
    invoiceType: 'individual' as const,
    revenue: 14500,
  },
  {
    id: '49',
    title: 'Financial Statements – FY 2025',
    status: 'Completed',
    client: { name: 'Lumo', color: '#22C55E' },
    serviceType: { label: 'Accounting', departmentId: 'dept-1' },
    teamLeads: [{ initials: 'MK', name: 'Mohammed Khan', color: '#334756' }],
    assignees: [{ initials: 'PN', name: 'Priya Nair', color: '#F16611' }],
    progress: 100,
    tasksCompleted: 16,
    tasksTotal: 16,
    dueDate: 'Due 30 Jun 2026',
    completedDate: '2026-06-28',
    badge: 0,
    invoiceType: 'bundled' as const,
    revenue: 5100,
  },
  {
    id: '50',
    title: 'WPS Registration Renewal',
    status: 'Completed',
    client: { name: 'Talvo', color: '#334756' },
    serviceType: { label: 'HR', departmentId: 'dept-5' },
    teamLeads: [{ initials: 'DK', name: 'David Kim', color: '#334756' }],
    assignees: [{ initials: 'YM', name: 'Yousef Mansour', color: '#22C55E' }],
    progress: 100,
    tasksCompleted: 8,
    tasksTotal: 8,
    dueDate: 'Due 15 May 2026',
    completedDate: '2026-05-19',
    badge: 0,
    invoiceType: 'individual' as const,
    revenue: 7400,
  },
  {
    id: '51',
    title: 'Legacy License Review – FY 2024',
    status: 'Archived',
    client: { name: 'Stratco', color: '#F16611' },
    serviceType: { label: 'Compliance', departmentId: 'dept-4' },
    teamLeads: [{ initials: 'OA', name: 'Omar Abdulla', color: '#F16611' }],
    assignees: [{ initials: 'BE', name: 'Bilal Ebrahim', color: '#F16611' }],
    progress: 100,
    tasksCompleted: 7,
    tasksTotal: 7,
    dueDate: 'Due 31 Jan 2025',
    badge: 0,
    invoiceType: 'bundled' as const,
    revenue: 4700,
  },
  {
    id: '52',
    title: 'Audit Working Papers – FY 2024',
    status: 'Archived',
    client: { name: 'Finovo', color: '#F16611' },
    serviceType: { label: 'Audit', departmentId: 'dept-3' },
    teamLeads: [{ initials: 'KT', name: 'Karim Tahir', color: '#F16611' }],
    assignees: [{ initials: 'RW', name: 'Rania Williams', color: '#22C55E' }],
    progress: 100,
    tasksCompleted: 13,
    tasksTotal: 13,
    dueDate: 'Due 28 Feb 2025',
    badge: 0,
    invoiceType: 'individual' as const,
    revenue: 10800,
  },
];

/* Stable label→departmentId mapping aligned with org mock-data.ts */
const LABEL_TO_DEPT_ID: Record<string, string> = {
  Accounting: 'dept-1',
  Finance:    'dept-2',
  Audit:      'dept-3',
  Compliance: 'dept-4',
  HR:         'dept-5',
  Technology: 'dept-6',
  IT:         'dept-6', // Technology dept covers IT
};

const GENERATED_PROJECTS: Project[] = Array.from({ length: 88 }, (_, index) => {
  const number = index + 53;
  const clients = [
    { name: 'Nexora', color: '#334756' },
    { name: 'Finovo', color: '#F16611' },
    { name: 'Lumo', color: '#22C55E' },
    { name: 'Stratco', color: '#F16611' },
    { name: 'Talvo', color: '#334756' },
    { name: 'Orvix', color: '#0A2B3B' },
  ];
  const services = ['Accounting', 'Audit', 'Finance', 'Compliance', 'HR', 'Technology'];
  const statuses: ProjectStatus[] = ['Current', 'Current', 'Overdue', 'On Hold', 'Completed', 'Archived'];
  const client = clients[index % clients.length];
  const status = statuses[index % statuses.length];
  const tasksTotal = 8 + (index % 8);
  const tasksCompleted =
    status === 'Completed' || status === 'Archived'
      ? tasksTotal
      : (index * 3) % (tasksTotal + 1);
  const month = String((index % 12) + 1).padStart(2, '0');
  const day = String((index * 3) % 25 + 1).padStart(2, '0');

  return {
    id: String(number),
    title: `${services[index % services.length]} Review – FY 2026 ${number}`,
    status,
    client,
    serviceType: { label: services[index % services.length], departmentId: LABEL_TO_DEPT_ID[services[index % services.length]] ?? '' },
    teamLeads: [{
      initials: ['AK', 'AM', 'DK', 'GH', 'KT', 'LN'][index % 6],
      name: ['Arjun Kumar', 'Aisha Mohammed', 'David Kim', 'Grace Hassan', 'Karim Tahir', 'Lina Noor'][index % 6],
      color: index % 2 === 0 ? '#F16611' : '#334756',
    }],
    assignees: [{
      initials: ['MK', 'TI', 'SN', 'TP', 'QA', 'EF'][index % 6],
      name: ['Mohammed Khan', 'Tariq Ibrahim', 'Sarah Nasser', 'Tina Patel', 'Qasim Ahmed', 'Elena Flores'][index % 6],
      color: index % 3 === 0 ? '#22C55E' : '#334756',
    }],
    progress: Math.round((tasksCompleted / tasksTotal) * 100),
    tasksCompleted,
    tasksTotal,
    dueDate: `Due ${day} ${new Date(2026, index % 12, 1).toLocaleString('en-US', { month: 'short' })} 2026`,
    ...(status === 'On Hold' ? { holdDate: `2026-${month}-${day}`, holdReason: 'Awaiting client information before work can continue.' } : {}),
    ...(status === 'Completed' ? { completedDate: `2026-${month}-${day}` } : {}),
    badge: index % 4,
    invoiceType: index % 2 === 0 ? 'bundled' : 'individual',
    revenue: 3500 + index * 275,
  };
});

export const MOCK_PROJECTS: Project[] = [...SEED_PROJECTS, ...GENERATED_PROJECTS];
