export type TaskStatus   = 'To Do' | 'In Progress' | 'Done' | 'Overdue' | 'On Hold' | 'Archived' | 'In Review' | 'Completed';
export type TaskPriority = 'Low' | 'Medium' | 'High' | 'Urgent';

export interface TaskProject {
  id:          string;
  title:       string;
  clientName:  string;
  clientColor: string;
}

export interface TaskItem {
  id:                string;
  name:              string;
  projects:          TaskProject[];          // supports multiple
  assignee:          { initials: string; name: string } | null;
  reassignmentNote?: string;
  status:            TaskStatus;
  priority:          TaskPriority;
  dueDate:           string;                 // ISO YYYY-MM-DD
  timeSpentSeconds:  number;
  comments:          number;
}

export const MOCK_TASKS: TaskItem[] = [
  {
    id: 't1',
    name: 'Collect VAT invoices from client',
    projects: [{ id: '1', title: 'VAT Filing Jul 2025 – Sep 2025', clientName: 'Nexora', clientColor: '#334756' }],
    assignee: { initials: 'MK', name: 'Mohammed Khan' },
    status: 'To Do',
    priority: 'High',
    dueDate: '2026-07-10',
    timeSpentSeconds: 5400,
    comments: 3,
  },
  {
    id: 't2',
    name: 'Reconcile bank statements for Q3',
    projects: [
      { id: '2',  title: 'Book Keeping – Sep 2025',   clientName: 'Finovo', clientColor: '#F16611' },
      { id: '29', title: 'Book Keeping – Oct 2025',   clientName: 'Finovo', clientColor: '#F16611' },
    ],
    assignee: { initials: 'TI', name: 'Tariq Ibrahim' },
    status: 'In Progress',
    priority: 'Medium',
    dueDate: '2026-07-15',
    timeSpentSeconds: 10800,
    comments: 1,
  },
  {
    id: 't3',
    name: 'Submit CT registration documents',
    projects: [{ id: '3', title: 'CT Registration – June 2026', clientName: 'Lumo', clientColor: '#22C55E' }],
    assignee: null,
    status: 'Overdue',
    priority: 'Urgent',
    dueDate: '2026-06-30',
    timeSpentSeconds: 0,
    comments: 0,
  },
  {
    id: 't4',
    name: 'Review payroll entries for October',
    projects: [{ id: '6', title: 'Payroll Management – Q4 2025', clientName: 'Stratco', clientColor: '#F16611' }],
    assignee: { initials: 'AT', name: 'Ali Tariq' },
    reassignmentNote: 'Reassigned from Omar Mansour',
    status: 'In Progress',
    priority: 'High',
    dueDate: '2026-08-05',
    timeSpentSeconds: 7200,
    comments: 5,
  },
  {
    id: 't5',
    name: 'Prepare final audit report',
    projects: [{ id: '7', title: 'Annual Audit – FY 2025', clientName: 'Nexora', clientColor: '#334756' }],
    assignee: { initials: 'TP', name: 'Tina Patel' },
    status: 'Done',
    priority: 'High',
    dueDate: '2025-05-01',
    timeSpentSeconds: 28800,
    comments: 12,
  },
  {
    id: 't6',
    name: 'Chase missing VAT receipts',
    projects: [{ id: '8', title: 'VAT Compliance – Jan 2026', clientName: 'Finovo', clientColor: '#F16611' }],
    assignee: { initials: 'SN', name: 'Sarah Nasser' },
    status: 'Overdue',
    priority: 'Urgent',
    dueDate: '2025-12-20',
    timeSpentSeconds: 3600,
    comments: 2,
  },
  {
    id: 't7',
    name: 'Draft corporate tax computation',
    projects: [{ id: '9', title: 'Corporate Tax Return – Q1 2026', clientName: 'Nexora', clientColor: '#334756' }],
    assignee: { initials: 'NS', name: 'Nadia Saleh' },
    reassignmentNote: 'Reassigned from Tina Patel',
    status: 'In Progress',
    priority: 'High',
    dueDate: '2026-08-08',
    timeSpentSeconds: 14400,
    comments: 4,
  },
  {
    id: 't8',
    name: 'Upload management accounts to portal',
    projects: [{ id: '10', title: 'Financial Statements – Mar 2026', clientName: 'Lumo', clientColor: '#22C55E' }],
    assignee: { initials: 'PN', name: 'Priya Nair' },
    status: 'To Do',
    priority: 'Medium',
    dueDate: '2026-08-22',
    timeSpentSeconds: 0,
    comments: 0,
  },
  {
    id: 't9',
    name: 'File corporate tax registration form',
    projects: [
      { id: '11', title: 'Corporate Tax Registration – FY 2026', clientName: 'Stratco', clientColor: '#F16611' },
      { id: '35', title: 'Corporate Tax Advisory – Q3',          clientName: 'Stratco', clientColor: '#F16611' },
    ],
    assignee: { initials: 'QA', name: 'Qasim Ahmed' },
    status: 'Overdue',
    priority: 'Urgent',
    dueDate: '2026-06-18',
    timeSpentSeconds: 1800,
    comments: 7,
  },
  {
    id: 't10',
    name: 'Obtain client signature on VAT form',
    projects: [{ id: '12', title: 'VAT Registration – Talvo', clientName: 'Talvo', clientColor: '#334756' }],
    assignee: { initials: 'YM', name: 'Yousef Mansour' },
    status: 'To Do',
    priority: 'Low',
    dueDate: '2026-08-30',
    timeSpentSeconds: 0,
    comments: 1,
  },
  {
    id: 't11',
    name: 'Complete WPS compliance check',
    projects: [{ id: '27', title: 'WPS Compliance Check – July', clientName: 'Talvo', clientColor: '#334756' }],
    assignee: { initials: 'YM', name: 'Yousef Mansour' },
    status: 'Overdue',
    priority: 'Urgent',
    dueDate: '2026-07-28',
    timeSpentSeconds: 900,
    comments: 0,
  },
  {
    id: 't12',
    name: 'Prepare payroll reconciliation schedule',
    projects: [{ id: '18', title: 'Payroll Reconciliation – Q2', clientName: 'Stratco', clientColor: '#F16611' }],
    assignee: { initials: 'TW', name: 'Thomas Wright' },
    status: 'Overdue',
    priority: 'High',
    dueDate: '2026-07-12',
    timeSpentSeconds: 5400,
    comments: 3,
  },
  {
    id: 't13',
    name: 'Update internal controls workpaper',
    projects: [{ id: '26', title: 'Internal Controls Review – Q3', clientName: 'Finovo', clientColor: '#F16611' }],
    assignee: { initials: 'SN', name: 'Sarah Nasser' },
    status: 'In Progress',
    priority: 'Medium',
    dueDate: '2026-09-01',
    timeSpentSeconds: 9000,
    comments: 2,
  },
  {
    id: 't14',
    name: 'Review year-end audit evidence binder',
    projects: [{ id: '14', title: 'Year-End Audit 2026 – Lumo', clientName: 'Lumo', clientColor: '#22C55E' }],
    assignee: { initials: 'TW', name: 'Thomas Wright' },
    reassignmentNote: 'Previously with Grace Hassan',
    status: 'In Progress',
    priority: 'High',
    dueDate: '2026-09-15',
    timeSpentSeconds: 18000,
    comments: 9,
  },
  {
    id: 't15',
    name: 'Send financial forecast to client',
    projects: [{ id: '28', title: 'Financial Forecast – H2 2026', clientName: 'Lumo', clientColor: '#22C55E' }],
    assignee: { initials: 'BE', name: 'Bilal Ebrahim' },
    status: 'To Do',
    priority: 'Medium',
    dueDate: '2026-08-25',
    timeSpentSeconds: 0,
    comments: 0,
  },
  {
    id: 't16',
    name: 'Submit regulatory filing documents',
    projects: [{ id: '17', title: 'Regulatory Filing – Orvix Q3', clientName: 'Orvix', clientColor: '#0A2B3B' }],
    assignee: { initials: 'GH', name: 'Grace Hassan' },
    status: 'To Do',
    priority: 'High',
    dueDate: '2026-09-25',
    timeSpentSeconds: 0,
    comments: 1,
  },
  {
    id: 't17',
    name: 'Reconcile VAT output for Q1',
    projects: [{ id: '32', title: 'VAT Reconciliation – Q1 2026', clientName: 'Finovo', clientColor: '#F16611' }],
    assignee: { initials: 'MK', name: 'Mohammed Khan' },
    status: 'Overdue',
    priority: 'Urgent',
    dueDate: '2026-07-15',
    timeSpentSeconds: 3600,
    comments: 6,
  },
  {
    id: 't18',
    name: 'Finalise VAT return workbook',
    projects: [{ id: '21', title: 'VAT Return – Q2 2026', clientName: 'Talvo', clientColor: '#334756' }],
    assignee: { initials: 'HS', name: 'Huda Saleh' },
    status: 'Done',
    priority: 'Medium',
    dueDate: '2026-08-10',
    timeSpentSeconds: 12600,
    comments: 4,
  },
  {
    id: 't19',
    name: 'Kick off budget planning meeting',
    projects: [{ id: '39', title: 'Budget Planning – FY 2027', clientName: 'Finovo', clientColor: '#F16611' }],
    assignee: { initials: 'NS', name: 'Nadia Saleh' },
    status: 'To Do',
    priority: 'Low',
    dueDate: '2026-09-10',
    timeSpentSeconds: 0,
    comments: 0,
  },
  {
    id: 't20',
    name: 'Payroll setup — new employee onboarding',
    projects: [{ id: '22', title: 'Payroll Setup – FY 2026', clientName: 'Nexora', clientColor: '#334756' }],
    assignee: { initials: 'OM', name: 'Omar Mansour' },
    status: 'In Progress',
    priority: 'Medium',
    dueDate: '2026-08-20',
    timeSpentSeconds: 7200,
    comments: 2,
  },
  {
    id: 't21',
    name: 'Prepare VAT return supporting schedule',
    projects: [{ id: '41', title: 'VAT Filing – Q3 2026', clientName: 'Nexora', clientColor: '#334756' }],
    assignee: { initials: 'HS', name: 'Huda Saleh' },
    status: 'In Progress',
    priority: 'High',
    dueDate: '2026-09-18',
    timeSpentSeconds: 5400,
    comments: 2,
  },
  {
    id: 't22',
    name: 'Review August bank reconciliation',
    projects: [{ id: '42', title: 'Monthly Close – August 2026', clientName: 'Talvo', clientColor: '#334756' }],
    assignee: { initials: 'MK', name: 'Mohammed Khan' },
    status: 'To Do',
    priority: 'Medium',
    dueDate: '2026-08-12',
    timeSpentSeconds: 0,
    comments: 1,
  },
  {
    id: 't23',
    name: 'Validate employee benefits register',
    projects: [{ id: '43', title: 'Employee Benefits Audit – 2026', clientName: 'Orvix', clientColor: '#0A2B3B' }],
    assignee: { initials: 'KS', name: 'Karen Simmons' },
    status: 'To Do',
    priority: 'Low',
    dueDate: '2026-10-01',
    timeSpentSeconds: 0,
    comments: 0,
  },
  {
    id: 't24',
    name: 'Complete audit planning checklist',
    projects: [{ id: '44', title: 'Internal Audit Plan – FY 2027', clientName: 'Stratco', clientColor: '#F16611' }],
    assignee: { initials: 'TP', name: 'Tina Patel' },
    status: 'Done',
    priority: 'High',
    dueDate: '2026-07-30',
    timeSpentSeconds: 21600,
    comments: 5,
  },
  {
    id: 't25',
    name: 'Gather missing corporate tax schedules',
    projects: [{ id: '45', title: 'Corporate Tax Return – Q2 2026', clientName: 'Lumo', clientColor: '#22C55E' }],
    assignee: { initials: 'QA', name: 'Qasim Ahmed' },
    status: 'Overdue',
    priority: 'Urgent',
    dueDate: '2026-07-25',
    timeSpentSeconds: 1800,
    comments: 4,
  },
  {
    id: 't26',
    name: 'Resolve payroll variance exceptions',
    projects: [{ id: '46', title: 'Payroll Reconciliation – July 2026', clientName: 'Finovo', clientColor: '#F16611' }],
    assignee: { initials: 'TW', name: 'Thomas Wright' },
    status: 'Overdue',
    priority: 'High',
    dueDate: '2026-07-05',
    timeSpentSeconds: 3600,
    comments: 3,
  },
  {
    id: 't27',
    name: 'Request updated valuation assumptions',
    projects: [{ id: '47', title: 'Business Valuation Review', clientName: 'Nexora', clientColor: '#334756' }],
    assignee: null,
    status: 'On Hold',
    priority: 'Urgent',
    dueDate: '2026-11-10',
    timeSpentSeconds: 900,
    comments: 2,
  },
  {
    id: 't28',
    name: 'Confirm disclosure documents with client',
    projects: [{ id: '48', title: 'VAT Voluntary Disclosure', clientName: 'Orvix', clientColor: '#0A2B3B' }],
    assignee: { initials: 'EF', name: 'Elena Flores' },
    status: 'On Hold',
    priority: 'Medium',
    dueDate: '2026-12-05',
    timeSpentSeconds: 1200,
    comments: 1,
  },
  {
    id: 't29',
    name: 'Archive signed financial statements',
    projects: [{ id: '49', title: 'Financial Statements – FY 2025', clientName: 'Lumo', clientColor: '#22C55E' }],
    assignee: { initials: 'PN', name: 'Priya Nair' },
    status: 'Done',
    priority: 'Medium',
    dueDate: '2026-06-28',
    timeSpentSeconds: 14400,
    comments: 3,
  },
  {
    id: 't30',
    name: 'File completed WPS renewal pack',
    projects: [{ id: '50', title: 'WPS Registration Renewal', clientName: 'Talvo', clientColor: '#334756' }],
    assignee: { initials: 'YM', name: 'Yousef Mansour' },
    status: 'Done',
    priority: 'Low',
    dueDate: '2026-05-15',
    timeSpentSeconds: 10800,
    comments: 2,
  },
  /* ── Not-started To Do tasks (timeSpentSeconds: 0) — ensure page 1 of Not Started tab is full ── */
  {
    id: 't33',
    name: 'Prepare client onboarding checklist',
    projects: [{ id: '53', title: 'Client Onboarding – Lumo Q3', clientName: 'Lumo', clientColor: '#22C55E' }],
    assignee: { initials: 'PN', name: 'Priya Nair' },
    status: 'To Do',
    priority: 'Medium',
    dueDate: '2026-07-20',
    timeSpentSeconds: 0,
    comments: 0,
  },
  {
    id: 't34',
    name: 'Verify deferred tax calculation',
    projects: [{ id: '54', title: 'Corporate Tax Review – Q3 2026', clientName: 'Nexora', clientColor: '#334756' }],
    assignee: { initials: 'NS', name: 'Nadia Saleh' },
    status: 'To Do',
    priority: 'High',
    dueDate: '2026-07-22',
    timeSpentSeconds: 0,
    comments: 0,
  },
  {
    id: 't35',
    name: 'Confirm transfer pricing documentation',
    projects: [{ id: '55', title: 'Transfer Pricing Study – 2026', clientName: 'Stratco', clientColor: '#F16611' }],
    assignee: { initials: 'TW', name: 'Thomas Wright' },
    status: 'To Do',
    priority: 'High',
    dueDate: '2026-07-26',
    timeSpentSeconds: 0,
    comments: 1,
  },
  {
    id: 't36',
    name: 'Distribute monthly management report',
    projects: [{ id: '56', title: 'Management Reporting – July 2026', clientName: 'Finovo', clientColor: '#F16611' }],
    assignee: { initials: 'MK', name: 'Mohammed Khan' },
    status: 'To Do',
    priority: 'Medium',
    dueDate: '2026-07-29',
    timeSpentSeconds: 0,
    comments: 0,
  },
  {
    id: 't37',
    name: 'Schedule Q3 audit kick-off meeting',
    projects: [{ id: '57', title: 'Q3 Audit Preparation – Talvo', clientName: 'Talvo', clientColor: '#334756' }],
    assignee: { initials: 'GH', name: 'Grace Hassan' },
    status: 'To Do',
    priority: 'Low',
    dueDate: '2026-08-03',
    timeSpentSeconds: 0,
    comments: 0,
  },
  {
    id: 't38',
    name: 'Send fee proposal to Orvix management',
    projects: [{ id: '58', title: 'Fee Review – FY 2026', clientName: 'Orvix', clientColor: '#0A2B3B' }],
    assignee: { initials: 'EF', name: 'Elena Flores' },
    status: 'To Do',
    priority: 'Medium',
    dueDate: '2026-08-06',
    timeSpentSeconds: 0,
    comments: 0,
  },
  {
    id: 't39',
    name: 'Update client contact details register',
    projects: [{ id: '59', title: 'CRM Update – August 2026', clientName: 'Nexora', clientColor: '#334756' }],
    assignee: { initials: 'QA', name: 'Qasim Ahmed' },
    status: 'To Do',
    priority: 'Low',
    dueDate: '2026-08-09',
    timeSpentSeconds: 0,
    comments: 0,
  },
  {
    id: 't40',
    name: 'Review draft engagement letter for renewal',
    projects: [{ id: '60', title: 'Engagement Renewal – Stratco', clientName: 'Stratco', clientColor: '#F16611' }],
    assignee: { initials: 'AT', name: 'Ali Tariq' },
    status: 'To Do',
    priority: 'High',
    dueDate: '2026-08-11',
    timeSpentSeconds: 0,
    comments: 2,
  },
  {
    id: 't31',
    name: 'Lock legacy license records',
    projects: [{ id: '51', title: 'Legacy License Review – FY 2024', clientName: 'Stratco', clientColor: '#F16611' }],
    assignee: { initials: 'BE', name: 'Bilal Ebrahim' },
    status: 'Archived',
    priority: 'Low',
    dueDate: '2025-01-31',
    timeSpentSeconds: 7200,
    comments: 0,
  },
  {
    id: 't32',
    name: 'Store prior-year audit evidence',
    projects: [{ id: '52', title: 'Audit Working Papers – FY 2024', clientName: 'Finovo', clientColor: '#F16611' }],
    assignee: { initials: 'RW', name: 'Rania Williams' },
    status: 'Archived',
    priority: 'Medium',
    dueDate: '2025-02-28',
    timeSpentSeconds: 9000,
    comments: 1,
  },
];
